name: Web
on: workflow_dispatch
jobs:
  HTML5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Libraries
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 8.0.2
          haxelib install openfl 9.2.1
          haxelib --never install flixel 4.11.0
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui 2.4.0
          haxelib git flixel-addons https://github.com/Ant643/flixel-addons  2.11.0 --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install hxCodec 2.5.1 --quiet
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib list


      - name: Compile
        run: haxelib run lime build html5 -final

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: html5Build
          path: export/release/html5/bin
          if-no-files-found: error
  Emscripten:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Emscripten Toolchain
        run: |
          cd ~
          git clone --quiet https://github.com/emscripten-core/emsdk.git > /dev/null
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          chmod +x ./emsdk_env.sh && echo 'source "/home/runner/emsdk/emsdk_env.sh"' >> $HOME/.bash_profile
          echo "EMSDK=$HOME/emsdk:$HOME/emsdk/upstream/emscripten" >> $GITHUB_ENV

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Configure Emscripten
        run: haxelib run lime config EMSCRIPTEN_SDK $EMSDK

      - name: Compile
        run: PATH=$EMSDK:$PATH haxelib run lime build emscripten -final

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: emscriptenBuild
          path: export/release/webassembly/bin
          if-no-files-found: error
